# Generated by Django 6.0.4 on 2026-04-28 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_size', models.PositiveIntegerField(verbose_name='Площадь участка (м²)')),
                ('passport_data', models.CharField(max_length=100, verbose_name='Паспортные данные')),
                ('cadastral_number', models.CharField(max_length=50, verbose_name='Кадастровый номер')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес участка')),
                ('payment_acquisitions', models.CharField(choices=[('rent', 'Аренда'), ('purchase', 'Покупка')], max_length=20, verbose_name='Вид приобретения')),
                ('building', models.CharField(choices=[('home', 'Дом'), ('shop', 'Магазин'), ('factory', 'Завод'), ('other', 'Другое')], max_length=25, verbose_name='Тип строения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Документы')),
                ('status', models.CharField(choices=[('new', 'На рассмотрении'), ('in_progress', 'В обработке'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
